### PR TITLE
[CSS | Sass | SCSS] - Fix namespace attribute selector issue

### LINKED ISSUE #174: CSS, Sass, SCSS - [attr|=value] pipe causes parser error
The `|` in the following attribute selector causes Gonzales to parser error out :fire:

``` css
[attr|=value] {
  content: 'foo';
}
```

### PR DESCRIPTION
**Pull request by bgriffith**
- Fixes a parse error when using `[attr|=value]`
- ~~Fixes a bug where SCSS and Sass would incorrectly create an ident containing the first character of the attributeMatch. For example if we had `[a*=b]`, the ident within the attributeName node would contain `a*`. This is fixed with the `checkIdentAttributeMatch` function.~~

This closes #174

### CODE REVIEW

File: src/css/parse.js [hunk 1]
```diff
@@ -3257,8 +3257,12 @@ function getNamespacePrefix() {
 function checkNamespaceSeparator(i) {
   if (i >= tokensLength) return 0;
 
-  if (tokens[i].type === TokenType.VerticalLine) return 1;
-  else return 0;
+  if (tokens[i].type === TokenType.VerticalLine) {
+    // Return false if `|=` - [attr|=value]
+    return (tokens[i + 1] && tokens[i + 1].type === TokenType.EqualsSign) ? 0 : 1;
+  }
```
Comment (tonyganch) [inline src/css/parse.js]: I find using only of style of either `if … else …` or ternary `… ? … : …` much easier to read:

``` js
if (tokens[i].type === TokenType.VerticalLine &&
    tokens[i + 1] && tokens[i + 1].type !== TokenType.EqualsSign) {
  return 1;
} else {
  return 0;
}
```

I assume here that there must be a token after `|` for it to be parsed as namespace separator, otherwise this should be a parsing error.

**Comment by tonyganch** [comment]
I'll take some time to think about `checkIdentAttributeMatch`, I'm not sure at the moment it won't cause errors in other cases.
We can separate the fix into two PRs: one for `|=` and another one for `*=` and I'm okay to merge the first one.

File: src/css/parse.js (hunk 1 above)
Comment (bgriffith) [inline src/css/parse.js]: Sorry about that. I've implemented the standard way for all 3 (CSS, Sass, SCSS). I also modified the conditional slightly to make it easier to read and improve code flow.

**Comment by bgriffith** [comment]
@tonyganch This PR has been updated to only contain the first fix `|=` :+1:
