### PR TITLE
[SCSS|Sass] Fix handling of interps in shash and typeSelector

### LINKED ISSUE #212: Multiple interps without prefix in selector cause parse error
The following code with cause a parse error.

``` scss
$foo: '.foo';
$bar: 'bar;

#{$foo}-#{$bar} {
  content: 'baz';
}
```

Dynamic ID's also causes an issue;

``` scss
$foo: 'foo';
$bar: 'bar;

##{$foo}-#{$bar} {
  content: 'baz';
}
```

While classes are ok;

``` scss
$foo: 'foo';
$bar: 'bar;

.#{$foo}-#{$bar} {
  content: 'baz';
}
```

### PR DESCRIPTION
**Pull request by bgriffith**
This PR adds the fixes issued for `class` and `parentSelector` to `shash` and `typeSelector` where multiple interps would cause a parse issue.

It also fixes issues with `number` when they follow an interp in `shash` and `typeSelector`.

It adds many tests for the `shash` and also creates a testing context for `typeSelector` for both Sass and SCSS;
### Tests: shash

```
##{$foo}
##{$foo}bar
##{$foo}1
##{$foo}#{$bar}
##{$foo}-bar
##{$foo}-1
##{$foo}-#{$bar}
##{$foo}a#{$bar}
##{$foo}1#{$bar}
##{$foo}--#{$bar}
```
### Tests: typeSelector

```
#{$foo}
#{$foo}bar
#{$foo}1
#{$foo}#{$bar}
#{$foo}-bar
#{$foo}-1
#{$foo}-#{$bar}
#{$foo}a#{$bar}
#{$foo}1#{$bar}
#{$foo}--#{$bar}
```

Fixes #212

### CODE REVIEW

File: src/sass/parse.js [hunk 1]
```diff
@@ -4177,34 +4180,68 @@ function getSC() {
...
 function checkShash(i) {
-  var l;
+  const start = i;
+  let l;
 
-  if (i >= tokensLength || tokens[i].type !== TokenType.NumberSign) return 0;
+  if (i >= tokensLength) return 0;
+
+  if (tokens[i].type === TokenType.NumberSign) {
+    if (checkInterpolation(i)) return 0;
```
Comment (tonyganch) [inline src/sass/parse.js:4157]: Why do we need to check for interpolation here? If that's the case then next character after `#` will be `{` which is an invalid ident and the check will fail.

File: src/sass/parse.js [hunk 2]
```diff
@@ -4177,34 +4180,68 @@ function getSC() {
...
+    i++;
+  } else return 0;
+
+  while (i < tokensLength) {
+    if (l = checkIdentOrInterpolation(i) || checkNumber(i)) i += l;
+    else if (tokens[i].type === TokenType.HyphenMinus) i += 1;
```
Comment (tonyganch) [inline src/sass/parse.js]: I've added `checkPartialIdent()` function (1) which should check if a string is `nmchar` according to the grammar (2). The function also has a getter which can be used in `getShash()`.

Do we want to check for that "partial ident" in every case we meet interpolation or are there any exceptions? If there are none, we could add `checkPartialIdent` inside `checkIdentOrInterpolation`.

(1): https://github.com/tonyganch/gonzales-pe/blob/dev/src/scss/parse.js#L1739
(2): https://www.w3.org/TR/CSS21/grammar.html

**Review by tonyganch — CHANGES_REQUESTED** [review]

File: src/sass/parse.js (hunk 1 above)
Comment (bgriffith) [reply src/sass/parse.js:4157]: You're totally correct - this is not needed. Moment of madness.

File: src/sass/parse.js (hunk 2 above)
Comment (bgriffith) [reply src/sass/parse.js]: Great! This will be very helpful!

I can't think of any exceptions off the top of my head, so on first thought putting it in `checkIdentOrInterpolation` would make perfect sense.

File: src/sass/parse.js (hunk 1 above)
Comment (bgriffith) [reply src/sass/parse.js:4157]: Cancel that - It's needed, because otherwise it will return an increased token index for `shash` even if it's not an ID. The example that fails is `tests/sass/selector/interp.1.sass` (`[a=b]#{$foo}`). Without this check, the code assumes the node starting with the `#` is an ID and not an interp.

**Comment by bgriffith** [comment]
@tonyganch I've just pushed some changes. `checkPartialIndent` has been added and the checks for hyphens have been removed. I've also had to update the node types of tests for `class`, `shash`, `selector` and `typeSelector` as a result of implementing partial idents.

**Comment by tonyganch** [comment]
Wow, that's marvellous amount of tests!
Thank you 🐙 

I've merged the PR with some fixes to make parser fail on examples like `.123`, see https://github.com/tonyganch/gonzales-pe/commit/28bfd6df513d59cf472e7971bed78556118f16e2
I'll wait with release a couple of days to see if we'll need a major version update.

**Comment by wytrych** [comment]
Could this fix be released please? I am currently unable to use `sasslint` because of this bug

**Comment by tonyganch** [comment]
Hey @wytrych, the release is planned for tomorrow, 17.11
